version: '3'


services:

  e-shop-app:
    container_name: e-shop-app
    image: zshri/e-shop:cafc6274d80e5e6c09f4d0bcadaeffb0a357df27
    environment:
      GHUB_CLIENT_ID: ${GHUB_CLIENT_ID}
      GHUB_CLIENT_SECRET: ${GHUB_CLIENT_SECRET}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      TEST_DB_USERNAME: ${TEST_DB_USERNAME}
      TEST_DB_PASSWORD: ${TEST_DB_PASSWORD}
    ports:
      - 80:8080
    networks:
      - e-shop-network
    restart: always
    depends_on:
      - e-shop-postgres
      - e-shop-redis


  e-shop-postgres:
    container_name: e-shop-postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: postgres-db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - .volumes/postgres-data:/var/lib/postgresql/data
    networks:
      - e-shop-network

  e-shop-postgres-test:
      container_name: e-shop-postgres-test
      image: postgres:14-alpine
      ports:
        - 5433:5433
      environment:
        POSTGRES_DB: postgres-db-test
        POSTGRES_USER: ${TEST_DB_USERNAME}
        POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
      volumes:
        - .volumes/postgres-data-test:/var/lib/postgresql/data


  e-shop-redis:
    container_name: e-shop-redis
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    volumes:
      - .volumes/e-shop-redis_data:/data
    networks:
      - e-shop-network

volumes:
  e-shop-postgres_data:
    driver: local
  e-shop-redis_data:
    driver: local

networks:
  e-shop-network:
    driver: bridge
