version: '3'

volumes:
  e-shop-postgres_data:
    driver: local
  e-shop-redis_data:
    driver: local

networks:
  e-shop-network:
    driver: bridge

services:

  e-shop-app:
    container_name: e-shop-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - e-shop-network
    env_file:
      - .env
#    environment:
#      - SPRING_PROFILES_ACTIVE=prod
#      - GITHUB_CLIENT_ID=6c0d9a5448fb9ea36d17
#      - GITHUB_CLIENT_SECRET=ced0bc566550b8044405d75ecdfacc8f2924c7cc

  e-shop-redis:
    container_name: e-shop-redis
    image: redis:latest
    ports:
      - 6379:6379
    command: redis-server --requirepass 123456789 --appendonly yes
    volumes:
      - .volumes/e-shop-redis_data:/data
    networks:
      - e-shop-network

  e-shop-postgres:
    container_name: e-shop-postgres
    image: postgres:14-alpine
    volumes:
      - .volumes/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres-db, e-shop-test-db
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: 12
    ports:
      - 5432:5432
    networks:
      - e-shop-network