
name: clean

on:
  workflow_dispatch:


jobs:

  deploy:
    runs-on: self-hosted

    steps:

      - name: Clean
        run: |
          docker stop $(docker ps -aq)
          docker system prune -a