name: pipeline

on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

  workflow_dispatch:

env:
  IMAGE_TAG: ${{ secrets.DOCKERHUB_USER }}/e-shop:${{ github.sha }}

jobs:

  build:
    runs-on: self-hosted

    steps:
      - name: Chown
        run: |
          sudo chown -R runner:runner /home/runner/actions-runner/      

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1


      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile-prod
          push: true
          tags: ${{ env.IMAGE_TAG }}